apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namePrefix: uat-
patchesStrategicMerge:
- deployment.yaml
- service.yaml
- secretproviderclass.yaml

patches:
- target:
    kind: Ingress
    name: patagonian-newsletter
    namespace: ptech-news
  path: ingress-patch.json
