apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: wordpress-db-password
spec:
  parameters:
    secrets: |
      - resourceName: "projects/patagonian-infra/secrets/SQL_UAT_NEWSLETTER/versions/latest"
        path: "password.txt"
  secretObjects:
    - secretName: uat-wordpress-db-password
      type: Opaque
      data: 
      - objectName: password.txt
        key: DB_PASSWORD