<?php
$kicker_slider_sc = kicker_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $kicker_slider_sc ) && strpos( $kicker_slider_sc, '[' ) !== false && strpos( $kicker_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( kicker_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$kicker_anchor_icon = kicker_get_theme_option( 'front_page_title_anchor_icon' );
		$kicker_anchor_text = kicker_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $kicker_anchor_icon ) || ! empty( $kicker_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $kicker_anchor_icon ) ? ' icon="' . esc_attr( $kicker_anchor_icon ) . '"' : '' )
									. ( ! empty( $kicker_anchor_text ) ? ' title="' . esc_attr( $kicker_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $kicker_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$kicker_scheme = kicker_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $kicker_scheme ) && ! kicker_is_inherit( $kicker_scheme ) ) {
			echo ' scheme_' . esc_attr( $kicker_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( kicker_get_theme_option( 'front_page_title_paddings' ) );
		if ( kicker_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$kicker_css      = '';
		$kicker_bg_image = kicker_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $kicker_bg_image ) ) {
			$kicker_css .= 'background-image: url(' . esc_url( kicker_get_attachment_url( $kicker_bg_image ) ) . ');';
		}
		if ( ! empty( $kicker_css ) ) {
			echo ' style="' . esc_attr( $kicker_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$kicker_anchor_icon = kicker_get_theme_option( 'front_page_title_anchor_icon' );
		$kicker_anchor_text = kicker_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $kicker_anchor_icon ) || ! empty( $kicker_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $kicker_anchor_icon ) ? ' icon="' . esc_attr( $kicker_anchor_icon ) . '"' : '' )
									. ( ! empty( $kicker_anchor_text ) ? ' title="' . esc_attr( $kicker_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( kicker_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' kicker-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$kicker_css      = '';
			$kicker_bg_mask  = kicker_get_theme_option( 'front_page_title_bg_mask' );
			$kicker_bg_color_type = kicker_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $kicker_bg_color_type ) {
				$kicker_bg_color = kicker_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $kicker_bg_color_type ) {
				$kicker_bg_color = kicker_get_scheme_color( 'bg_color', $kicker_scheme );
			} else {
				$kicker_bg_color = '';
			}
			if ( ! empty( $kicker_bg_color ) && $kicker_bg_mask > 0 ) {
				$kicker_css .= 'background-color: ' . esc_attr(
					1 == $kicker_bg_mask ? $kicker_bg_color : kicker_hex2rgba( $kicker_bg_color, $kicker_bg_mask )
				) . ';';
			}
			if ( ! empty( $kicker_css ) ) {
				echo ' style="' . esc_attr( $kicker_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$kicker_caption = kicker_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $kicker_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $kicker_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $kicker_caption, 'kicker_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$kicker_description = kicker_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $kicker_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $kicker_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $kicker_description ), 'kicker_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( kicker_get_theme_option( 'front_page_title_button1_link' ) != '' || kicker_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						kicker_show_layout( kicker_customizer_partial_refresh_front_page_title_button1_link() );
						kicker_show_layout( kicker_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
