# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
    paths:
      - code/**
jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Set DOCKER_IMAGE"
        run: |
          echo "DOCKER_IMAGE=gcr.io/patagonian-infra/ptechnews:$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Build, tag, and push image
        id: build-image
        run: |
          # Build and push $DOCKER_IMAGE to GCR
          cd code
          docker build -t $DOCKER_IMAGE .
          echo "Pushing image to GCR..."
          gcloud auth configure-docker -q
          docker push $DOCKER_IMAGE
          echo "New docker image $DOCKER_IMAGE ready"
          rm -rf ../gha-creds-*.json
          echo "::set-output name=docker_image::$DOCKER_IMAGE"
    outputs:
      docker_image: ${{ steps.build-image.outputs.docker_image }}

  deploy-dev:
    name: Deploy to Dev
    needs: build
    environment: uat
    runs-on: ubuntu-latest
    steps:
      - name: Get Manifest File
        uses: actions/checkout@v2

      - name: Update Version UAT
        env:
          docker_image: ${{ needs.build.outputs.docker_image }}
        run: |
            version=$(cat ./k8s/uat/deployment.yaml | grep image: | awk '{print $2}' | sed 's/\//\\\//g')
            docker_image=$(echo $docker_image | sed 's/\//\\\//g')
            sed -i "s/$version/$docker_image/g" ./k8s/uat/deployment.yaml
            
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Version updated for UAT

  deploy-prod:
    name: Deploy to Prod
    needs: [build,deploy-dev]
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Get Manifest File
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Update Version PROD
        run: |
          version=$(cat ./k8s/prod/deployment.yaml | grep image: | awk '{print $2}' | sed 's/\//\\\//g')
          docker_image=$(echo ${{ needs.build.outputs.docker_image }} | sed 's/\//\\\//g')
          sed -i "s/$version/$docker_image/g" ./k8s/prod/deployment.yaml
            
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Version updated for PROD