# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
    paths:
      - code/**
      - .github/**
jobs:
  build:
    name: Build and Pushing the Image
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Build, tag, and push image 
      id: build-image
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        SERVICE_NAME: ptechnews
      run: |
        # Build a docker container and push it to GCR
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        cd code
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$git_hash .
        echo "Pushing image to GCR..."
        gcloud auth configure-docker -q
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$git_hash
        echo "::set-output name=image::gcr.io/$PROJECT_ID/$SERVICE_NAME:$git_hash"
        
    - name: Update Version UAT
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        SERVICE_NAME: ptechnews
      run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          version=$(cat ./k8s/uat/deployment.yaml | grep image: | awk '{print $2}' | sed 's/\//\\\//g')
          sed -i "s/$version/gcr.io\/$PROJECT_ID\/$SERVICE_NAME:$git_hash/g" ./k8s/uat/deployment.yaml
          rm -rf gha-creds-*.json
          
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Version updated